# Deep learning 기초

In [6]:
import torch
import numpy as np

In [2]:
from google.colab import drive
drive.mount('/content/data') # 드라이브 연결

Mounted at /content/data


In [3]:
data = [
    [1,2],[3,4],[5,6]
]
data

[[1, 2], [3, 4], [5, 6]]

In [4]:
data_tensor = torch.tensor(data)
data_tensor # tensor 가 붙으면 torch 형태로 바뀐거다 

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [8]:
arr = np.array(data) 
arr_tensor = torch.from_numpy(arr) # array를 tensor로 만듬 

print(f'Numpy arr value: \n {arr} \n')
print(f'Tensor arr_tensor value: \n {arr_tensor}')

Numpy arr value: 
 [[1 2]
 [3 4]
 [5 6]] 

Tensor arr_tensor value: 
 tensor([[1, 2],
        [3, 4],
        [5, 6]])


In [9]:
np.multiply(arr, 2, out=arr)

print(f'Numpy arr after * 2 operation: \n {arr} \n') # arr에 *2
print(f'Tensor arr_tensor value after modifying numpy array: \n {arr_tensor}')

Numpy arr after * 2 operation: 
 [[ 2  4]
 [ 6  8]
 [10 12]] 

Tensor arr_tensor value after modifying numpy array: 
 tensor([[ 2,  4],
        [ 6,  8],
        [10, 12]])


In [10]:
data_tensor

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [11]:
x_ones = torch.ones_like(data_tensor) # 같은 shape에 1로 채움 
x_ones

tensor([[1, 1],
        [1, 1],
        [1, 1]])

In [12]:
x_rand = torch.rand_like(data_tensor,dtype=torch.float) # 랜덤으로 실수형 데이터 생성 
x_rand

tensor([[0.7079, 0.9968],
        [0.0921, 0.4554],
        [0.6910, 0.9102]])

In [13]:
shape = (2,2,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f'Random Tensor:\n {rand_tensor}\n')
print(f'ones Tensor:\n {ones_tensor}\n')
print(f'Zeros Tensor:\n {zeros_tensor}\n')

Random Tensor:
 tensor([[0.6899, 0.2839],
        [0.0265, 0.5530]])

ones Tensor:
 tensor([[1., 1.],
        [1., 1.]])

Zeros Tensor:
 tensor([[0., 0.],
        [0., 0.]])



In [15]:
tensor = torch.rand(3,4)

print(f'Shape of tensor:{tensor.shape}')
print(f'Datatype of tensor : {tensor.dtype}')
print(f'Device tensor is stored on {tensor.device}')

Shape of tensor:torch.Size([3, 4])
Datatype of tensor : torch.float32
Device tensor is stored on cpu


In [16]:
if torch.cuda.is_available():
    tensor = tensor.to('cuda')
  
tensor.device

device(type='cuda', index=0)