In [2]:
import torch
import numpy as np

In [2]:
from google.colab import drive
drive.mount('/content/data') # 드라이브 연결

Mounted at /content/data


## Indexing and slicing

In [3]:
data = [
    [1, 2, 3], [4, 5, 6], [7, 8, 9]
]
tensor = torch.tensor(data, dtype=torch.float)

print(tensor)
print('-'*50)

print('First row: ',tensor[0])
print('Last row: ',tensor[-1])
print('First column: ', tensor[:, 0])
print('Last column1:', tensor[:, -1])
print('Last column2:', tensor[..., -1])

print('-'*50)
tensor[:,1] = 0
tensor[1] = 0
print(tensor)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])
--------------------------------------------------
First row:  tensor([1., 2., 3.])
Last row:  tensor([7., 8., 9.])
First column:  tensor([1., 4., 7.])
Last column1: tensor([3., 6., 9.])
Last column2: tensor([3., 6., 9.])
--------------------------------------------------
tensor([[1., 0., 3.],
        [0., 0., 0.],
        [7., 0., 9.]])


## 합치기

In [4]:
t0 = torch.cat([tensor,tensor],dim=0) # 아래(세로) 방향으로 합쳐짐 
t0

tensor([[1., 0., 3.],
        [0., 0., 0.],
        [7., 0., 9.],
        [1., 0., 3.],
        [0., 0., 0.],
        [7., 0., 9.]])

In [6]:
t1 = torch.cat([tensor , tensor],dim=1) # 옆(가로)방향으로 합쳐짐 
t1

tensor([[1., 0., 3., 1., 0., 3.],
        [0., 0., 0., 0., 0., 0.],
        [7., 0., 9., 7., 0., 9.]])

## 연산

### mm

In [7]:
mat1 = torch.randn(2,3)
mat2 = torch.randn(3,3)

In [8]:
torch.mm(mat1,mat2)

tensor([[ 0.6948,  1.6920,  1.6678],
        [-2.0412,  0.7632, -0.8185]])

In [9]:
a = torch.randn(3)
a

tensor([-0.3313,  0.9081,  1.2482])

In [10]:
torch.mul(a,100) # 곱하기 100

tensor([-33.1255,  90.8139, 124.8184])

In [11]:
b= torch.randn(4,1)
b

tensor([[1.5340],
        [1.1764],
        [0.0396],
        [0.0671]])

In [12]:
c = torch.randn(1,4)
c

tensor([[ 0.2034, -1.1824,  0.3367, -2.5133]])

### mul

In [4]:
a = torch.randn(3)
a

tensor([0.2059, 1.2217, 1.4045])

In [41]:
torch.mul(a, 100)

tensor([  6.9603,  18.2217, -12.4322])

In [5]:
b = torch.randn(4, 1)
b

tensor([[ 0.7378],
        [ 1.8697],
        [-1.0906],
        [-1.8591]])

In [43]:
c = torch.randn(1, 4)
c

tensor([[ 0.3639, -1.4806, -0.1369, -1.2771]])

In [44]:
torch.mul(b, c)

tensor([[-0.0612,  0.2490,  0.0230,  0.2148],
        [ 0.4921, -2.0025, -0.1852, -1.7273],
        [ 0.0215, -0.0876, -0.0081, -0.0755],
        [-0.0797,  0.3245,  0.0300,  0.2799]])

In [6]:
torch.mul(a, b)

tensor([[ 0.1519,  0.9014,  1.0362],
        [ 0.3850,  2.2843,  2.6260],
        [-0.2246, -1.3324, -1.5317],
        [-0.3828, -2.2713, -2.6111]])

### matmul

In [30]:
# vector x vector
tensor1 = torch.randn(3)
tensor2 = torch.randn(3)
torch.matmul(tensor1, tensor2).size()

torch.Size([])

In [31]:
torch.matmul(tensor1, tensor2)

tensor(1.6557)

In [34]:
# matrix x vector
tensor1 = torch.randn(3, 4)
tensor2 = torch.randn(4)
torch.matmul(tensor1, tensor2).size()

tensor([ 2.6781, -0.8003, -2.8217])

In [33]:
torch.matmul(tensor1, tensor2)

tensor([ 0.0641, -1.1939,  0.6056])

In [45]:
# batched matrix x broadcasted vector
tensor1 = torch.randn(10, 3, 4)
tensor2 = torch.randn(4)
torch.matmul(tensor1, tensor2).size()

torch.Size([10, 3])

In [46]:
# batched matrix x broadcasted matrix
tensor1 = torch.randn(10, 3, 4)
tensor2 = torch.randn(4, 5)
torch.matmul(tensor1, tensor2).size()

torch.Size([10, 3, 5])

### single-element tensors

In [47]:
tensor2

tensor([[-1.4262,  0.1412, -1.6226,  0.9442,  0.7641],
        [ 1.7496, -0.0321, -1.8625,  0.1908, -0.2854],
        [ 0.0750,  0.0804, -0.8499, -0.3875,  0.7876],
        [-1.7880, -0.7055,  1.7378,  0.2288,  0.5228]])

In [48]:
agg = tensor2.sum()
agg

tensor(-1.7374)

In [ ]:
agg_item = agg.item() # tensor -> python
agg_item

## Inplace operations

In [50]:
print(tensor2, "\n")
print(f"{tensor2.add(5)}\n")
print('-'*50)
print(tensor2, "\n")
tensor2.add_(5) # inplace
print(tensor2)

tensor([[-1.4262,  0.1412, -1.6226,  0.9442,  0.7641],
        [ 1.7496, -0.0321, -1.8625,  0.1908, -0.2854],
        [ 0.0750,  0.0804, -0.8499, -0.3875,  0.7876],
        [-1.7880, -0.7055,  1.7378,  0.2288,  0.5228]]) 

tensor([[3.5738, 5.1412, 3.3774, 5.9442, 5.7641],
        [6.7496, 4.9679, 3.1375, 5.1908, 4.7146],
        [5.0750, 5.0804, 4.1501, 4.6125, 5.7876],
        [3.2120, 4.2945, 6.7378, 5.2288, 5.5228]])

--------------------------------------------------
tensor([[-1.4262,  0.1412, -1.6226,  0.9442,  0.7641],
        [ 1.7496, -0.0321, -1.8625,  0.1908, -0.2854],
        [ 0.0750,  0.0804, -0.8499, -0.3875,  0.7876],
        [-1.7880, -0.7055,  1.7378,  0.2288,  0.5228]]) 

tensor([[3.5738, 5.1412, 3.3774, 5.9442, 5.7641],
        [6.7496, 4.9679, 3.1375, 5.1908, 4.7146],
        [5.0750, 5.0804, 4.1501, 4.6125, 5.7876],
        [3.2120, 4.2945, 6.7378, 5.2288, 5.5228]])


## Bridge with Numpy

In [51]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


In [52]:
t.add_(1)
print(f"t: {t}")
print(f"n: {n}") # ???!!!!!

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


## Dimension Change

In [53]:
x = torch.rand(2,3,4) # 2*3*4 =24    (1,24),(2*12),(3*8),(4,6)
x.reshape(2,-1) # (2,12)
x.reshape(-1,4) # (6,4)
x.reshape(1,-1) # (1,24)
x.reshape(3,4,2) # (3,4,2)

### permute()

In [54]:
x = torch.rand(16,32,3)
x.shape

torch.Size([16, 32, 3])

In [ ]:
x.permute(2,1,0) # 위치만 변경 [3,32,16]

In [ ]:
x.permute(0,2,1) # 위치만 변경 [16,3,32]

### squeeze(),unsqueeze()

In [58]:
x = torch.rand(1, 3, 1, 20, 1) # 1*3*1*20*1 =60
x.shape

torch.Size([1, 3, 1, 20, 1])

In [59]:
x.squeeze().shape 

torch.Size([3, 20])

In [60]:
x.squeeze(dim=0).shape

torch.Size([3, 1, 20, 1])

In [61]:
x.squeeze(dim=-1).shape

torch.Size([1, 3, 1, 20])

In [62]:
x.squeeze(dim=2).shape

torch.Size([1, 3, 20, 1])

In [63]:
x = torch.rand(3, 20, 128)
x.shape

torch.Size([3, 20, 128])

In [64]:
x.unsqueeze(dim=1).shape

torch.Size([3, 1, 20, 128])