## 벡터화 연산

In [124]:
x = np.arange(1,10001)
y = np.arange(10001, 20001)

z = x+y
z

array([10002, 10004, 10006, ..., 29996, 29998, 30000])

In [126]:
a = np.array([1,2,3,4])
b = np.array([4,2,2,4])
c = np.array([1,2,3,4])

np.all(a == b) # 다 같으면 TRUE , 아니면 FALSE

array([False,  True, False,  True])

## 차원 축소 연산

In [128]:
x = np.array([1,2,3,4])
np.sum(x)

10

In [131]:
x = np.arange(12).reshape(3,-1)
x.sum(axis=0) # 세로로 더한다 (행간 더한다)
x.sum(axis=1) # 가로로 더한다 (열간 더한다)

array([ 6, 22, 38])

In [134]:
x = np.arange(20).reshape(2,5,-1)
np.min(x)
x.min(axis=0)
np.min(x,axis=1)
x.min(axis=2)

0

In [ ]:
x = np.arange(20).reshape(2,5,-1)
np.argmin(x)
x.argmin(axis=0)
np.argmin(x,axis=1)
x.argmin(axis=2)            # 해당 배열의 제일 작은 값의 인덱스를 반환

In [ ]:
x = np.arange(20).reshape(2,5,-1)
np.max(x)
x.max(axis=0)
np.max(x,axis=1)
x.mix(axis=2)

In [ ]:
x = np.arange(20).reshape(2,5,-1)
np.argmax(x)
x.argmax(axis=0)
np.argmax(x,axis=1)
x.argmax(axis=2)

In [ ]:
x.mean() # 평균 구하기
np.median(x) # 중앙값 구하기 

In [135]:
a = np.array([1,2,3,2])
b = np.array([2,2,3,2])
c = np.array([6,4,4,5])
((a<=b) & (b<=c)).all()

True