# 넘파이 배열

In [2]:
import numpy as np
ar = np.array([i for i in range(10)])
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
ar2 = np.array([0.1,5,4,12])
ar2 

array([ 0.1,  5. ,  4. , 12. ])

## 1차원 배열 만들기

## - 배열의 연산

In [7]:
x = np.array([1,2,3],dtype='f')
x[0] + x[1]

dtype('float32')

In [9]:
x = np.array([1,2,3],dtype='U')
x[0] + x[1]

'12'

In [10]:
x=[0,1,-1,0]
y=[1,0,0,0]
x/y # 계산 불가능

TypeError: unsupported operand type(s) for /: 'list' and 'list'

In [11]:
xn = np.array(x)
yn = np.array(y)
xn/yn # 계산이 가능하다 

C:\Users\User\AppData\Local\Temp\ipykernel_6536\3742454558.py:3: RuntimeWarning: divide by zero encountered in true_divide
  xn/yn
C:\Users\User\AppData\Local\Temp\ipykernel_6536\3742454558.py:3: RuntimeWarning: invalid value encountered in true_divide
  xn/yn


array([  0.,  inf, -inf,  nan])

In [15]:
a = [1,2,3]
b = [10,20,30]
2 * a + b 

[1, 2, 3, 1, 2, 3, 10, 20, 30]

In [16]:
an = np.array(a)
bn = np.array(b)
2 * an + bn

array([12, 24, 36])

## 2차원 배열 만들기

In [18]:
c = np.array([[0,1,2],[3,4,5]])
c

array([[0, 1, 2],
       [3, 4, 5]])

In [19]:
print(len(c))
print(len(c[0]))

2
3


In [21]:
a = np.array([[10,20,30,40],[50,60,70,80]])
a

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

## 3차원 배열 만들기

In [24]:
d = np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]],
            [[11,12,13,14],[15,16,17,18],[19,20,21,22]]])  #2*3*4 배열
d

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[11, 12, 13, 14],
        [15, 16, 17, 18],
        [19, 20, 21, 22]]])

In [28]:
len(d) , len(d[0]) , len(d[0][0]) 

(2, 3, 4)

In [29]:
d.ndim # 차원을 알려줌

3

## 배열 생성

In [61]:
c = np.zeros((5,2),dtype='i')
c

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]], dtype=int32)

In [73]:
d = np.zeros(5 , dtype='u4')
d

array([0, 0, 0, 0, 0], dtype=uint32)

In [65]:
e = np.ones((2,3,4),dtype='i8')
e

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int64)

In [66]:
f = np.ones_like(b,dtype='f') # 다른 배열과 같은 형태의 배열 1로 생성
f

array([1., 1., 1.], dtype=float32)

In [67]:
g = np.empty((4,3))
g # 특정한 값으로 초기화 하지 않는 명령

array([[1.20146721e-311, 3.16202013e-322, 0.00000000e+000],
       [0.00000000e+000, 1.06099790e-312, 1.21544426e-046],
       [2.04040627e+184, 3.99777772e+175, 7.69887646e+169],
       [3.57579757e-061, 1.69380911e-052, 1.00628941e-046]])

In [ ]:
np.arange(10)
np.arange(3,21,2) # (시작 , 끝(포함x) , 단계)

In [25]:
ex = np.linspace(0,100,5) # 100을 5개로 분할
ex2 = np.logspace(0,100,5) # 로그 100을 5개로 분할
ex

array([  0.,  25.,  50.,  75., 100.])

In [75]:
A = np.array([[1,2,3],[4,5,6]])
A.T # 헹렬 변환 

array([[1, 4],
       [2, 5],
       [3, 6]])

In [77]:
a = np.arange(12)  # 배열의 크기 변경
b = a.reshape(3,4) # 3,4 배열 만들어줌

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [78]:
a.reshape(3,-1) # 알아서 맞춰주는 느낌

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [23]:
np.full((3,3,3), '',dtype='U10')

array([[['', '', ''],
        ['', '', ''],
        ['', '', '']],

       [['', '', ''],
        ['', '', ''],
        ['', '', '']],

       [['', '', ''],
        ['', '', ''],
        ['', '', '']]], dtype='<U10')