## 연습문제

In [122]:
a =  np.ones((3,2))
b =  np.zeros((3,3))
c = np.arange(10,160,10).reshape(3,5)
k = np.hstack([b,a])
k2 = np.vstack([k,c])
k3 = np.tile(k2,(2,1))
k3

array([[  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.]])

## 연습문제

In [142]:
practice = np.array([[1.1, 7.1, 8.0, 2.1, 6.5, 7.2],
                                [2.7, 5.2, 3.3, 9.0, 7.7, 2.8],
                                [0.7, 8.8, 4.2, 8.9, 4.3, 7.4],
                                [8.2, 1.1, 5.4, 2.9, 6.9, 0.2],
                                [7.4, 4.8, 2.7, 3.1, 2.8, 8.9]])

np.max(practice)
practice.sum(axis=0)
practice.sum(axis=0)
practice.mean(axis=1)
practice.min(axis=1)

array([1.1, 2.7, 0.7, 0.2, 2.7])

## 연습문제

In [22]:
scores = np.array([[ 1, 2 , 3 , 4],[46,99,100,71],[81,59,90,100]])
k=np.argsort(scores[1,:]) # 영어 성적열 기준으로 인덱스 추출
scores[:,k]

array([[  1,   4,   2,   3],
       [ 46,  71,  99, 100],
       [ 81, 100,  59,  90]])

## 연습문제

In [209]:
np.random.seed(0)
k = np.random.choice(2,100)
sum(k)/len(k)

0.56

In [6]:
import numpy as np
np.random.seed(0)
a = np.random.randint(1,7,size=100)
np.mean(a)

3.42