In [1]:
from google.colab import drive
drive.mount('/content/data') # 드라이브 연결

Mounted at /content/data


In [3]:
%matplotlib inline
import torch

x = torch.ones(5) #input
y = torch.zeros(3) #output

w = torch.randn(5, 3, requires_grad=True) # weight 
b = torch.randn(3, requires_grad=True) # bias

z = torch.matmul(x,w)+b #wx+b

loss = torch.nn.functional.binary_cross_entropy_with_logits(z,y) # 예측값(z) , 실제값(y) 차이

tensor([ 1.7577, -2.5064,  1.8667], grad_fn=<AddBackward0>)

In [4]:
print('Gradient function for z =',z.grad_fn) # 경사하강법
print('Gradient function for loss',loss.grad_fn)

Gradient function for z = <AddBackward0 object at 0x7fbff3538be0>
Gradient function for loss <BinaryCrossEntropyWithLogitsBackward0 object at 0x7fbff35389a0>


## computing gradients

In [8]:
loss.backward() # 업데이트(학습 이후에 항상 해야함)
print(w.grad)
print(b.grad)

tensor([[0.2843, 0.0251, 0.2887],
        [0.2843, 0.0251, 0.2887],
        [0.2843, 0.0251, 0.2887],
        [0.2843, 0.0251, 0.2887],
        [0.2843, 0.0251, 0.2887]])
tensor([0.2843, 0.0251, 0.2887])


In [ ]:
z = torch.matmul(x, w)+b # 학습 구현 (train)
print(z.requires_grad)

with torch.no_grad(): # 실험하는 데이터 구현 (test)
    z = torch.matmul(x, w)+b
print(z.requires_grad)