In [1]:
import numpy as np

## 연습문제


In [5]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array(([7,8,9],[10,11,12]))
a+b



array([[ 8, 10, 12],
       [14, 16, 18]])

In [12]:
a = np.arange(1,7).reshape(2,3)
b= np.arange(7,13).reshape(2,3)
a+b

array([[ 8, 10, 12],
       [14, 16, 18]])

In [19]:
a = np.array([i*3 for i in range(1,10)])
a 

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27])

In [24]:
c = np.zeros(10)
c[4]=1
c

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [46]:
d = np.arange(50)
d[::-1] # 마지막 숫자가 증감인데 -1 이면 역순으로 가져오게된다  처음:끝-1:증감

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [48]:
np.empty((3,3,3),dtype='U10')

array([[['', '', ''],
        ['', '', ''],
        ['', '', '']],

       [['', '', ''],
        ['', '', ''],
        ['', '', '']],

       [['', '', ''],
        ['', '', ''],
        ['', '', '']]], dtype='<U10')

In [49]:
np.full((3,3,3), '',dtype='U10')

array([[['', '', ''],
        ['', '', ''],
        ['', '', '']],

       [['', '', ''],
        ['', '', ''],
        ['', '', '']],

       [['', '', ''],
        ['', '', ''],
        ['', '', '']]], dtype='<U10')

In [51]:
np.full((3,3,3), 'playdata',dtype='U8')

array([[['playdata', 'playdata', 'playdata'],
        ['playdata', 'playdata', 'playdata'],
        ['playdata', 'playdata', 'playdata']],

       [['playdata', 'playdata', 'playdata'],
        ['playdata', 'playdata', 'playdata'],
        ['playdata', 'playdata', 'playdata']],

       [['playdata', 'playdata', 'playdata'],
        ['playdata', 'playdata', 'playdata'],
        ['playdata', 'playdata', 'playdata']]], dtype='<U8')

In [58]:
k = np.array([i for i in range(1,41) if i % 2 == 0]).reshape(2,2,5)
k

array([[[ 2,  4,  6,  8, 10],
        [12, 14, 16, 18, 20]],

       [[22, 24, 26, 28, 30],
        [32, 34, 36, 38, 40]]])

In [87]:
np.random.seed(0)
k = np.random.randint(2,size=9)
k.astype('bool').reshape(3,3)

array([[False,  True,  True],
       [False,  True,  True],
       [ True,  True,  True]])

In [76]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [91]:
np.random.seed(0)
k2 =np.random.rand(10) * 10
k2.astype('int')

array([5, 7, 6, 5, 4, 6, 4, 8, 9, 3])

In [137]:
g = np.ones((10,10))
g[1:-1,1:-1] = 0
g

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [119]:
g2 = np.ones((10,10))
g2[0:-1,[0,-1]] = 0 
g2[[0,-1],:] =0
g2

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [177]:
k = np.ones((8,8))
k[1:8:2,0:7:2] =0
k[0:7:2,1:8:2] =0  # 슬라이싱으로 증감 표현이 가능하다
k

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

In [11]:
a = np.eye(2)
np.tile(a,(4,4))

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

In [178]:
a = np.arange(1,11)
a2 = np.array([-i if i>3 and i <7 else i for i in range(1,11)])
a2

array([ 1,  2,  3, -4, -5, -6,  7,  8,  9, 10])

In [24]:
## 다른방법
a = np.arange(11)
a[(3<a) & (7>a)] *=-1
print(a)

[ 0  1  2  3 -4 -5 -6  7  8  9 10]


In [181]:
a3 = np.array([i for i in range(1,101) if i % 3 == 0 ])
np.sum(a3)

1683

In [31]:
k = np.linspace(0.1,0.9,9)
k

array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [13]:
# 풀이1
while True:
    number = int(input("자연수만 입력해주세요."))
    try:
        if number <=0:
            continue;
        k = [np.random.choice(range(1, 46), size=6, replace=False) for _ in range(number)]
        display(np.sort(k)) # 보여주는 명령어 
        break;
    except ValueError:
        continue;

자연수만 입력해주세요. 4


array([[12, 14, 17, 34, 37, 43],
       [ 1,  5, 18, 20, 21, 40],
       [10, 15, 20, 23, 26, 39],
       [ 6,  7, 10, 12, 15, 26]])

In [ ]:
# 풀이 2
while True:
    try:
        count = int(input('로또 몇개 드릴까요?'))
        if count <=0:
            raise Error
        lottos = [np.sort(np.random.chocie(range(1,46),size=6,replace=False)) for i in range(count)]
        display(lottos)
        break
    except:
        print('자연수만 입력하세요')

로또 몇개 드릴까요? 5


자연수만 입력하세요


In [3]:
resp_time = np. array([158, 85, 205, 24, 42, 175, 188, 149, 153, 171, 137, 55, 108,
199, 177, 209, 218, 76, 103, 189, 110, 192, 136, 119, 4, 102,
177, 212, 110, 37, 163, 32, 77, 22, 125, 184, 46, 139, 72,
168, 133, 209, 148, 47, 102, 65, 160, 56, 11, 96, 169, 118,
55, 135, 217, 49, 100, 85, 179, 15, 139, 199, 124, 142, 15,
49, 168, 171, 168, 177, 147, 23, 199, 26, 51, 42, 90, 128,
186, 169, 129, 70, 198, 111, 81, 150, 17, 177, 201, 10, 75,
199, 55, 151, 183, 152, 119, 193, 110, 204])

len(resp_time[resp_time>200])
(resp_time>200).sum()

8

In [6]:
np.quantile(resp_time,0.25) # 1분위수
np.quantile(resp_time,0.5)  # 2분위수 
np.quantile(resp_time,0.75) # 3분위수
np.quantile(resp_time,1)    # 4분위수

218

In [50]:
p = ["뽀로로", "루피", "크롱"]
result = np.array([2, 1, 2, 2, 2, 2, 0, 2, 1, 1, 0, 0, 2, 0, 0, 1, 1, 2, 2, 2, 1, 1,
1, 2, 0, 2, 2, 0, 1, 1, 0, 2, 1, 0, 1, 2, 0, 0, 1, 0, 1, 1, 1, 2,
1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 2, 0, 2, 2, 0, 0, 1, 1, 1, 0, 0, 2,
2, 1, 0, 1, 2, 0, 2, 0, 0, 0, 2, 0, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0,
2, 0, 0, 0, 0, 2, 1, 2, 0, 2, 0, 0, 1, 0, 1, 2, 1, 2, 0, 2, 2, 1,
2, 0, 0, 1, 1, 0, 1, 2, 1, 2, 0, 2, 2, 2, 2, 0, 2, 2, 0, 2, 0, 2,
1, 1, 2, 1, 1, 0, 0, 1, 0, 0, 0, 2, 2, 0, 2, 0, 0, 0, 2, 0, 0, 0,
2, 0, 1, 2, 1, 0, 2, 0, 0, 1, 2, 1, 1, 2, 2, 0, 0, 0, 0, 2, 2, 1,
0, 1, 1, 2, 2, 1, 0, 0, 2, 0, 0, 0, 2, 0, 2, 2, 0, 2, 1, 0, 0, 2,
0, 1])

a=len(result[result==0]) 
b=len(result[result==1]) 
c=len(result[result==2]) 

d = {a:p[0],b:p[1],c:p[2]}

print('{}가 {}표로 반장으로 선출 되었습니다'.format(d[max(d)],max(d)))

뽀로로가 81표로 반장으로 선출 되었습니다


In [66]:
# 다른 풀이 
a = np.bincount(result, minlength=3)
b = a.argmax()
print(f"{p[b]}가 {a[b]}표로 반장으로 선출되었습니다.")

뽀로로가 81표로 반장으로 선출되었습니다.


In [68]:
# 다른 풀이2
index, count = np.unique(result, return_counts=True)
winner = count.argmax()

print(f"{p[winner]}가 {np.max(count)}표로 반장으로 선출되었습니다.")

뽀로로가 81표로 반장으로 선출되었습니다.


In [69]:
# 다른 풀이3
count = np.bincount(result , minlength=3)
winner_index = count.argmax()
print(f'{p[winner_index]}가 {count[winner_index]}표로 반장으로 선출되었습니다.')

뽀로로가 81표로 반장으로 선출되었습니다.
