# 넘파이 배열

In [2]:
import numpy as np
ar = np.array([i for i in range(10)])
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
ar2 = np.array([0.1,5,4,12])
ar2 

array([ 0.1,  5. ,  4. , 12. ])

## 1차원 배열 만들기

## - 배열의 연산

In [7]:
x = np.array([1,2,3],dtype='f')
x[0] + x[1]

dtype('float32')

In [9]:
x = np.array([1,2,3],dtype='U')
x[0] + x[1]

'12'

In [10]:
x=[0,1,-1,0]
y=[1,0,0,0]
x/y # 계산 불가능

TypeError: unsupported operand type(s) for /: 'list' and 'list'

In [11]:
xn = np.array(x)
yn = np.array(y)
xn/yn # 계산이 가능하다 

C:\Users\User\AppData\Local\Temp\ipykernel_6536\3742454558.py:3: RuntimeWarning: divide by zero encountered in true_divide
  xn/yn
C:\Users\User\AppData\Local\Temp\ipykernel_6536\3742454558.py:3: RuntimeWarning: invalid value encountered in true_divide
  xn/yn


array([  0.,  inf, -inf,  nan])

In [15]:
a = [1,2,3]
b = [10,20,30]
2 * a + b 

[1, 2, 3, 1, 2, 3, 10, 20, 30]

In [16]:
an = np.array(a)
bn = np.array(b)
2 * an + bn

array([12, 24, 36])

## 2차원 배열 만들기

In [18]:
c = np.array([[0,1,2],[3,4,5]])
c

array([[0, 1, 2],
       [3, 4, 5]])

In [19]:
print(len(c))
print(len(c[0]))

2
3


In [21]:
a = np.array([[10,20,30,40],[50,60,70,80]])
a

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

## 3차원 배열 만들기

In [24]:
d = np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]],
            [[11,12,13,14],[15,16,17,18],[19,20,21,22]]])  #2*3*4 배열
d

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[11, 12, 13, 14],
        [15, 16, 17, 18],
        [19, 20, 21, 22]]])

In [28]:
len(d) , len(d[0]) , len(d[0][0]) 

(2, 3, 4)

In [29]:
d.ndim # 차원을 알려줌

3

## 배열의 인덱싱

In [30]:
a  = np.array([0,1,2,3,4])
print(a[2]) # 2
print(a[-1]) # 4

2
4


In [ ]:
a = np.array([[0,1,2] ,[3,4,5]])
a[0,0] # 0
a[0,1] # 1
a[-1,-1] # 5

## 배열의 슬라이싱

In [39]:
a = np.array([[0,1,2,3],[4,5,6,7]])
a[0, :] # 첫번째 행 전체 0,1,2,3
a[:,1]  # 두번쨰 열 전체 1,5
a[1,1:]  # 5,6,7
a[:2,:2] #[0,1] , [4,5]

array([[0, 1],
       [4, 5]])

In [42]:
lit = [[1,2,3,4] , [5,6,7,8]]
lit[0][0:3]

[1, 2, 3]

In [57]:
m = np.array([[0,1,2,3,4],[5,6,7,8,9],[10,11,12,13,14]])

m[1,2] 
m[2,-1]
m[1,1:3]
m[1:3,2]
m[0:2,3:5]

array([[3, 4],
       [8, 9]])

## 배열 생성

In [61]:
c = np.zeros((5,2),dtype='i')
c

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]], dtype=int32)

In [73]:
d = np.zeros(5 , dtype='u4')
d

array([0, 0, 0, 0, 0], dtype=uint32)

In [65]:
e = np.ones((2,3,4),dtype='i8')
e

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int64)

In [66]:
f = np.ones_like(b,dtype='f') # 다른 배열과 같은 형태의 배열 1로 생성
f

array([1., 1., 1.], dtype=float32)

In [67]:
g = np.empty((4,3))
g # 특정한 값으로 초기화 하지 않는 명령

array([[1.20146721e-311, 3.16202013e-322, 0.00000000e+000],
       [0.00000000e+000, 1.06099790e-312, 1.21544426e-046],
       [2.04040627e+184, 3.99777772e+175, 7.69887646e+169],
       [3.57579757e-061, 1.69380911e-052, 1.00628941e-046]])

In [ ]:
np.arange(10)
np.arange(3,21,2) # (시작 , 끝(포함x) , 단계)

In [25]:
ex = np.linspace(0,100,5) # 100을 5개로 분할
ex2 = np.logspace(0,100,5) # 로그 100을 5개로 분할
ex

array([  0.,  25.,  50.,  75., 100.])

In [75]:
A = np.array([[1,2,3],[4,5,6]])
A.T # 헹렬 변환 

array([[1, 4],
       [2, 5],
       [3, 6]])

In [77]:
a = np.arange(12)  # 배열의 크기 변경
b = a.reshape(3,4) # 3,4 배열 만들어줌

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [78]:
a.reshape(3,-1) # 알아서 맞춰주는 느낌

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [23]:
np.full((3,3,3), '',dtype='U10')

array([[['', '', ''],
        ['', '', ''],
        ['', '', '']],

       [['', '', ''],
        ['', '', ''],
        ['', '', '']],

       [['', '', ''],
        ['', '', ''],
        ['', '', '']]], dtype='<U10')

## 배열의 크기 변형

In [80]:
a.flatten() # 1차원 형태로 만들어줌
a.ravel()# 1차원 형태로 만들어줌

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [81]:
a[:,np.newaxis] # 1차원 증가시키는 경우

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11]])

## 배열 연결

In [85]:
b1 = np.ones((3,3))
b2 = np.zeros((3,3))
np.hstack([b1,b2]) # 수평으로 합쳐줌(행의 개수가 같아야함)

array([[1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.]])

In [86]:
a1 = np.ones((2,3))
a2 = np.zeros((3,3))
np.vstack([a1,a2]) # 수직으로 합쳐줌

array([[1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [87]:
c1 = np.ones((3,4))
c2 = np.zeros((3,4))
np.dstack([c1,c2]) #안쪽 원소의 차원 증가

array([[[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]]])

In [ ]:
np.stack([c1,c2],axis=0) # 가장 바깥 값이 2인 차원이 추가(통으로 추가)


In [ ]:
d1 =  np.ones((4,5))
d2 =  np.zeros((4,5))
d3 = np.arange(20).reshape(4,5)

In [16]:
np.stack([d1,d2,d3],axis=0)

array([[[ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.]],

       [[ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.]],

       [[ 0.,  1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.,  9.],
        [10., 11., 12., 13., 14.],
        [15., 16., 17., 18., 19.]]])

In [17]:
np.stack([d1,d2,d3],axis=0).shape

(3, 4, 5)

In [93]:
np.stack([d1,d2,d3],axis=1) #가로 

array([[[ 1.,  1.,  1.,  1.,  1.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  1.,  2.,  3.,  4.]],

       [[ 1.,  1.,  1.,  1.,  1.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 5.,  6.,  7.,  8.,  9.]],

       [[ 1.,  1.,  1.,  1.,  1.],
        [ 0.,  0.,  0.,  0.,  0.],
        [10., 11., 12., 13., 14.]],

       [[ 1.,  1.,  1.,  1.,  1.],
        [ 0.,  0.,  0.,  0.,  0.],
        [15., 16., 17., 18., 19.]]])

In [18]:
np.stack([d1,d2,d3],axis=1).shape

(4, 3, 5)

In [94]:
np.stack([d1,d2,d3],axis=2) #세로

array([[[ 1.,  0.,  0.],
        [ 1.,  0.,  1.],
        [ 1.,  0.,  2.],
        [ 1.,  0.,  3.],
        [ 1.,  0.,  4.]],

       [[ 1.,  0.,  5.],
        [ 1.,  0.,  6.],
        [ 1.,  0.,  7.],
        [ 1.,  0.,  8.],
        [ 1.,  0.,  9.]],

       [[ 1.,  0., 10.],
        [ 1.,  0., 11.],
        [ 1.,  0., 12.],
        [ 1.,  0., 13.],
        [ 1.,  0., 14.]],

       [[ 1.,  0., 15.],
        [ 1.,  0., 16.],
        [ 1.,  0., 17.],
        [ 1.,  0., 18.],
        [ 1.,  0., 19.]]])

In [19]:
np.stack([d1,d2,d3],axis=2).shape

(4, 5, 3)

In [ ]:
a = np.array([0,1,2],[3,4,5]])
np.tile(a,2) # 반복을 시켜줌 

## 연습문제

In [122]:
a =  np.ones((3,2))
b =  np.zeros((3,3))
c = np.arange(10,160,10).reshape(3,5)
k = np.hstack([b,a])
k2 = np.vstack([k,c])
k3 = np.tile(k2,(2,1))
k3

array([[  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.]])

## 벡터화 연산

In [124]:
x = np.arange(1,10001)
y = np.arange(10001, 20001)

z = x+y
z

array([10002, 10004, 10006, ..., 29996, 29998, 30000])

In [126]:
a = np.array([1,2,3,4])
b = np.array([4,2,2,4])
c = np.array([1,2,3,4])

np.all(a == b) # 다 같으면 TRUE , 아니면 FALSE

array([False,  True, False,  True])

## 차원 축소 연산

In [128]:
x = np.array([1,2,3,4])
np.sum(x)

10

In [131]:
x = np.arange(12).reshape(3,-1)
x.sum(axis=0) # 세로로 더한다 (행간 더한다)
x.sum(axis=1) # 가로로 더한다 (열간 더한다)

array([ 6, 22, 38])

In [134]:
x = np.arange(20).reshape(2,5,-1)
np.min(x)
x.min(axis=0)
np.min(x,axis=1)
x.min(axis=2)

0

In [ ]:
x = np.arange(20).reshape(2,5,-1)
np.argmin(x)
x.argmin(axis=0)
np.argmin(x,axis=1)
x.argmin(axis=2)            # 해당 배열의 제일 작은 값의 인덱스를 반환

In [ ]:
x = np.arange(20).reshape(2,5,-1)
np.max(x)
x.max(axis=0)
np.max(x,axis=1)
x.mix(axis=2)

In [ ]:
x = np.arange(20).reshape(2,5,-1)
np.argmax(x)
x.argmax(axis=0)
np.argmax(x,axis=1)
x.argmax(axis=2)

In [ ]:
x.mean() # 평균 구하기
np.median(x) # 중앙값 구하기 

In [135]:
a = np.array([1,2,3,2])
b = np.array([2,2,3,2])
c = np.array([6,4,4,5])
((a<=b) & (b<=c)).all()

True

## 연습문제

In [142]:
practice = np.array([[1.1, 7.1, 8.0, 2.1, 6.5, 7.2],
                                [2.7, 5.2, 3.3, 9.0, 7.7, 2.8],
                                [0.7, 8.8, 4.2, 8.9, 4.3, 7.4],
                                [8.2, 1.1, 5.4, 2.9, 6.9, 0.2],
                                [7.4, 4.8, 2.7, 3.1, 2.8, 8.9]])

np.max(practice)
practice.sum(axis=0)
practice.sum(axis=0)
practice.mean(axis=1)
practice.min(axis=1)

array([1.1, 2.7, 0.7, 0.2, 2.7])

## 정렬

In [143]:
a = np.array([42,38,12,25])
j=np.argsort(a)
j   # 숫자 작은거 순서대로 인덱스만 추출해줌

array([2, 3, 1, 0], dtype=int64)

In [144]:
a[j]

array([12, 25, 38, 42])

In [145]:
np.sort(a)

array([12, 25, 38, 42])

In [147]:
a = np.array([[1,2],[3,4],[5,6]])
print(a[[0,1,2], [0,1,0]])  # 0,1,2 -> 행  /  0,1,0 -> 열  따라서 1,4,5
print(a[:, [0,1,0]])   # : -> 행 / 0,1,0 -> 열 (행이 0일때 0,1,0값 , 행이1일때 0,1,0값 , 행이 2일대 0,1,0값)

[1 4 5]
[[1 2 1]
 [3 4 3]
 [5 6 5]]


## 연습문제

In [22]:
scores = np.array([[ 1, 2 , 3 , 4],[46,99,100,71],[81,59,90,100]])
k=np.argsort(scores[1,:]) # 영어 성적열 기준으로 인덱스 추출
scores[:,k]

array([[  1,   4,   2,   3],
       [ 46,  71,  99, 100],
       [ 81, 100,  59,  90]])

## 시드 설정하기

In [189]:
np.random.seed(0)
np.random.rand(10)
np.random.seed(0)
np.random.rand(10)
# 시드가 같으면 같은 숫자가 만들어진다 

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ,
       0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152])

## 데이터 순서 바꾸기

In [196]:
x = np.arange(10)
np.random.shuffle(x)
x

array([0, 9, 2, 3, 5, 6, 7, 1, 8, 4])

## 데이터 샘플링

In [ ]:
np.random.chocie(5,5,replace=False) # 5개중에서 5개 뽑는데 같은거 안뽑음 (비복원)  / True 면 복원
np.random.choice(5,3,replace=False) # 5개중에서 3개만 선택 (비복원) / True 면 복원
np.random.choice(5,10) # 반복해서 10개 선택 (복원)
np.random.choice(5,10, p=[0.1,0,0.3,0.6,0]) # 10개 뽑는데 각각 확률도 지정

In [ ]:
np.random.rand(10) # 0~1사이 균일한 확률분포 실수 난수 생성
np.random.rand(3,5) # 0~1사이 균일한 확률분포 실수 난수(3,5) 형태로 생성
np.random.randn(10) # 평균이 0이고 표준편차가 1인 표준정규분포 난수 생성
np.random.randn(3,5) # 평균이 0이고 표준편차가 1인 표준정규분포 난수 (3,5)형태로 생성 

In [ ]:
np.random.randint(10,size=10) # 10미만 10개 뽑기
np.random.randint(10,20,size=10) # 10 ~ 20 사이 10개 뽑기 
np.random.randint(10,20,size=(3,5)) # 10~20사이 (3.5)로 뽑기

## 연습문제

In [209]:
np.random.seed(0)
k = np.random.choice(2,100)
sum(k)/len(k)

0.56

In [6]:
import numpy as np
np.random.seed(0)
a = np.random.randint(1,7,size=100)
np.mean(a)

3.42

## 정수 데이터 카운팅

In [214]:
np.unique([11,11,2,2,34,34])
a = np.array(['a','b','b','c','a'])
index , count = np.unique(a,return_counts=True)
index
count

array([2, 2, 1], dtype=int64)

In [215]:
np.bincount([1,1,2,2,2,3,],minlength=6) # 0부터 6-1=5 숫자에 대해 각각 카운트를 해줌 
# 0 1번 / 1 2번 / 2 3번 / 3 1번 / 4,5 0번 

array([0, 2, 3, 1, 0, 0], dtype=int64)