## 배열의 인덱싱

In [30]:
a  = np.array([0,1,2,3,4])
print(a[2]) # 2
print(a[-1]) # 4

2
4


In [ ]:
a = np.array([[0,1,2] ,[3,4,5]])
a[0,0] # 0
a[0,1] # 1
a[-1,-1] # 5

## 배열의 슬라이싱

In [39]:
a = np.array([[0,1,2,3],[4,5,6,7]])
a[0, :] # 첫번째 행 전체 0,1,2,3
a[:,1]  # 두번쨰 열 전체 1,5
a[1,1:]  # 5,6,7
a[:2,:2] #[0,1] , [4,5]

array([[0, 1],
       [4, 5]])

In [42]:
lit = [[1,2,3,4] , [5,6,7,8]]
lit[0][0:3]

[1, 2, 3]

In [57]:
m = np.array([[0,1,2,3,4],[5,6,7,8,9],[10,11,12,13,14]])

m[1,2] 
m[2,-1]
m[1,1:3]
m[1:3,2]
m[0:2,3:5]

array([[3, 4],
       [8, 9]])

## 배열의 크기 변형

In [80]:
a.flatten() # 1차원 형태로 만들어줌
a.ravel()# 1차원 형태로 만들어줌

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [81]:
a[:,np.newaxis] # 1차원 증가시키는 경우

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11]])

## 배열 연결

In [85]:
b1 = np.ones((3,3))
b2 = np.zeros((3,3))
np.hstack([b1,b2]) # 수평으로 합쳐줌(행의 개수가 같아야함)

array([[1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.]])

In [86]:
a1 = np.ones((2,3))
a2 = np.zeros((3,3))
np.vstack([a1,a2]) # 수직으로 합쳐줌

array([[1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [87]:
c1 = np.ones((3,4))
c2 = np.zeros((3,4))
np.dstack([c1,c2]) #안쪽 원소의 차원 증가

array([[[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]]])

In [ ]:
np.stack([c1,c2],axis=0) # 가장 바깥 값이 2인 차원이 추가(통으로 추가)


In [ ]:
d1 =  np.ones((4,5))
d2 =  np.zeros((4,5))
d3 = np.arange(20).reshape(4,5)

In [16]:
np.stack([d1,d2,d3],axis=0)

array([[[ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.]],

       [[ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.]],

       [[ 0.,  1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.,  9.],
        [10., 11., 12., 13., 14.],
        [15., 16., 17., 18., 19.]]])

In [17]:
np.stack([d1,d2,d3],axis=0).shape

(3, 4, 5)

In [93]:
np.stack([d1,d2,d3],axis=1) #가로 

array([[[ 1.,  1.,  1.,  1.,  1.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  1.,  2.,  3.,  4.]],

       [[ 1.,  1.,  1.,  1.,  1.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 5.,  6.,  7.,  8.,  9.]],

       [[ 1.,  1.,  1.,  1.,  1.],
        [ 0.,  0.,  0.,  0.,  0.],
        [10., 11., 12., 13., 14.]],

       [[ 1.,  1.,  1.,  1.,  1.],
        [ 0.,  0.,  0.,  0.,  0.],
        [15., 16., 17., 18., 19.]]])

In [18]:
np.stack([d1,d2,d3],axis=1).shape

(4, 3, 5)

In [94]:
np.stack([d1,d2,d3],axis=2) #세로

array([[[ 1.,  0.,  0.],
        [ 1.,  0.,  1.],
        [ 1.,  0.,  2.],
        [ 1.,  0.,  3.],
        [ 1.,  0.,  4.]],

       [[ 1.,  0.,  5.],
        [ 1.,  0.,  6.],
        [ 1.,  0.,  7.],
        [ 1.,  0.,  8.],
        [ 1.,  0.,  9.]],

       [[ 1.,  0., 10.],
        [ 1.,  0., 11.],
        [ 1.,  0., 12.],
        [ 1.,  0., 13.],
        [ 1.,  0., 14.]],

       [[ 1.,  0., 15.],
        [ 1.,  0., 16.],
        [ 1.,  0., 17.],
        [ 1.,  0., 18.],
        [ 1.,  0., 19.]]])

In [19]:
np.stack([d1,d2,d3],axis=2).shape

(4, 5, 3)

In [ ]:
a = np.array([0,1,2],[3,4,5]])
np.tile(a,2) # 반복을 시켜줌 

## 정렬

In [143]:
a = np.array([42,38,12,25])
j=np.argsort(a)
j   # 숫자 작은거 순서대로 인덱스만 추출해줌

array([2, 3, 1, 0], dtype=int64)

In [144]:
a[j]

array([12, 25, 38, 42])

In [145]:
np.sort(a)

array([12, 25, 38, 42])

In [147]:
a = np.array([[1,2],[3,4],[5,6]])
print(a[[0,1,2], [0,1,0]])  # 0,1,2 -> 행  /  0,1,0 -> 열  따라서 1,4,5
print(a[:, [0,1,0]])   # : -> 행 / 0,1,0 -> 열 (행이 0일때 0,1,0값 , 행이1일때 0,1,0값 , 행이 2일대 0,1,0값)

[1 4 5]
[[1 2 1]
 [3 4 3]
 [5 6 5]]


## 데이터 순서 바꾸기

In [196]:
x = np.arange(10)
np.random.shuffle(x)
x

array([0, 9, 2, 3, 5, 6, 7, 1, 8, 4])

## 정수 데이터 카운팅

In [214]:
np.unique([11,11,2,2,34,34])
a = np.array(['a','b','b','c','a'])
index , count = np.unique(a,return_counts=True)
index
count

array([2, 2, 1], dtype=int64)

In [215]:
np.bincount([1,1,2,2,2,3,],minlength=6) # 0부터 6-1=5 숫자에 대해 각각 카운트를 해줌 
# 0 1번 / 1 2번 / 2 3번 / 3 1번 / 4,5 0번 

array([0, 2, 3, 1, 0, 0], dtype=int64)